before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

deploy:production:
  stage: deploy
  image: ruby:latest
  only:
    - main
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
